azure:
  resourceGroup: reeve
  functionApp:
    name: video-processor
    zipFile: function_app.zip
  openAI:
    endpoint: https://azureoai-sc.openai.azure.com
    apiKey: 9K0b0yLuKhmMckS6SwHczuD0Bq3suB4rNDBxaO53yD01exM8zXEUJQQJ99BGACfhMk5XJ3w3AAABACOGYR47
    embeddingModelName: text-embedding-3-large
    embeddingDeploymentName: text-embedding-3-large
    embeddingDimensions: 3072
  aiService:
    name: aifoundry-sc
    subscriptionKey: 4XucCryuQl8uNk9mtl4y6Eahfb9RUxI7UKowrFoHZgdwoN9sxVA8JQQJ99BGACfhMk5XJ3w3AAAAACOGwJeL
  searchService:
    name: aisearch-sc
    clientKey: 6cHwTrdch10jRVePg3Hs2NzrUcEQr85mkpWRo9rQ0EAzSeDoirxS
    indexName: video-index
  storage:
    accountName: blobstoragesc
    connectionString: DefaultEndpointsProtocol=https;AccountName=blobstoragesc;AccountKey=GbDmjQAXrbMn3FQqNbbhdpMs1Jw9KxuC6Ww0FpAnaZMt/1QADaPbDyzUbRXoPQd+gAJRPbe8vu/T+AStA7HwjA==;EndpointSuffix=core.windows.net
    blobContainerName: videos
    
